// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.apache.spark.bts.deal.entity


/** 
$Id$
$Revision$
$Date$
$Name$
@Filename DT_IFG001908_BTS_2.xsd
@Generator IFMS 5.0
@GeneratedAt 2016-04-13 06:54:21 UTC

*/


/** 
*Deal Key Value Detail* is a generic ad hoc extension of deal with a value with specified semantics in a "key-value" manner (semantics is specified by the attribute name; value can be free text, currency amount or reference to a business object instance).
Particular implemented structure enables:
1. define values of attributes linked to particular deal instance ("extended attributes of deal") or
2. define equivalent identifiers (synonyms) of chosen deal business unique identifier or
3. one or more references in deal to other business objects ("foreign keys") or
4. define values of attributes of sub-entities associated with/dependent on the deal (e.g. if a deal requires as detail to capture the "merge price" per FI involved in a merger business transaction then it can be done by defining the sub-entity name).
5. store a ordered sequence of values per extension attribute (semantics of the ordering must be defined elsewhere).
Note: If many deals need certain/similar detail data structure with several attributes it should be considered to design and implemented specialization of DealDetailData object to achieve better performance and/or more efficient data validation.
@State QC2passed

*/
case class DealDetail(DealAttr: Seq[org.apache.spark.bts.deal.entity.DetailAttribute] = Nil,
  SubEntity: Seq[org.apache.spark.bts.deal.entity.DetailSubEntity] = Nil)
      


/** 
Key value attributes that provide the additional details
@State QC2passed

*/
case class DetailAttribute(Role: Short,
  Attr: org.apache.spark.bts.deal.entity.Attribute)
      


/** 
Attribute with Key Value Pair
@State QC2passed

*/
case class Attribute(Key: Short,
  Value: Seq[org.apache.spark.bts.deal.entity.AttributeValue] = Nil)
      


/** 
Attribute Value
@State QC2passed

*/
case class AttributeValue(SeqNo: Short,
  Ctgy: Short,
  BusObjId: Option[String] = None,
  BusObjIdScCd: Option[Short] = None,
  TxtVal: Option[String] = None,
  DecVal: Option[BigDecimal] = None,
  AmtVal: Option[org.apache.spark.bts.deal.entity.Amount] = None,
  Date: Option[String] = None)
      


/** 
Detail Sub entity
@State QC2passed

*/
case class DetailSubEntity(Name: Int,
  SubEntId: String,
  SubEntIdScCd: Int,
  Attr: Seq[org.apache.spark.bts.deal.entity.Attribute] = Nil)
      


/** 
Transaction Element Referenced Business object
@State DTcandidate

*/
case class TransationElementReferencedObj(SacNo: Option[String] = None,
  SacNoScCd: Option[Short] = None,
  FinInstrId: Option[String] = None,
  FinInstrIdScCd: Option[Short] = None,
  SecPosId: Option[String] = None,
  SecPosIdScCd: Option[Short] = None)
      


/** 
Transaction Reference
@State QC2passed

*/
case class TransactionReference(Id: String,
  IdScCd: Short)
      


/** 
Transaction Detail
@State QC2passed

*/
case class TransactionDetail(TrxAttr: Seq[org.apache.spark.bts.deal.entity.DetailAttribute] = Nil,
  SubEntity: Seq[org.apache.spark.bts.deal.entity.DetailSubEntity] = Nil)
      


/** 
Generalization of business objects which can be the (primary) deal scope or detail value for a atrtibute/property/key of a deal.
For example: bank legal entity, bank business unit ... bank relationship, banking agreement, financial instrument ...
This object contains for the referenced business object also the mandatory or known parent objects (referenced via internal unique Id) => enables basic searching and aggregation of deals in BTS.
For example:
1. If the referenced object is a FI event then FI and FI issuer could be filled as parent reference too.
2. If the referenced object is SKA then also following parent references could be filled:
bank relationship, bank business unit.
3. If the referenced object is securities position then also following parentv references could be filled:
FI, FI issuer, SKA, bank relationship, bank business unit.
Notes:
- Impementation R.0.2 - discriminator of scope object.
- Counter party of a deal has no derived parent references.
- Attributes of counter party shall be either implemented directly in deal or in a separate entity (with key: deal number, sequence number within deal) but then used only as reference value in deal key value detail.
@State QC2passed

*/
case class DealContext(BusObjCtgyCd: Short,
  BusObjId: String,
  BusObjIdScCd: Short,
  BankUnitId: String,
  BankUnitIdScCd: Short,
  BankRelId: String,
  BankRelIdScCd: Short)
      


/** 
*Transaction* is a core extension of deal which when processed issue booking requests directly to XBS or DBH. This object contains the attributes on the level of the deal and is parent for the sub-entities with additional detail data.

The "id" and "idScCD" together form the business unique key on the Transaction.
All attributes with String[256] are values from external systems and do not have fixed lengths for their values. For e.g. the "id" value comes from different systems and each of them have their own id definitions.
@State QC2passed

*/
case class Transaction(Header: org.apache.spark.bts.deal.entity.Header,
  Id: String,
  IdScCd: Short,
  TpCd: Short,
  StsCd: Short,
  TradeDate: Option[String] = None,
  ValueDate: Option[String] = None,
  BookingDate: Option[String] = None,
  SettlDate: Option[String] = None,
  DealLink: org.apache.spark.bts.deal.entity.DealReference,
  TrxLink: Seq[org.apache.spark.bts.deal.entity.TransactionLink] = Nil,
  Reversal: Option[org.apache.spark.bts.deal.entity.TrxReversal] = None,
  Detail: Option[org.apache.spark.bts.deal.entity.TransactionDetail] = None)
      


/** 
Reference to Deal
@State QC2passed

*/
case class DealReference(Id: String,
  IdScCd: Short)
      


/** 
*Deal* represents the bank internal image of the external request/trigger/event or its enrichment with processing details or any sub-task/sub-process generated or created on behalves of the original deal. Deal is hence any separately identifiable processing decomposition unit down to the lowest level request which is executed as one logical unit of work - e.g. booking request to XBS (with requests for particular money bookings of GFM) or DBH (with requests for particular instrument bookings/contexts of Securities Order).

The "id" and "idScCD" together form the business unique key on the Deal.
All attributes with String[256] are values from external systems and do not have fixed lengths for their values. For e.g. the "id" value comes from different systems and each of them have their own id definitions.
@State DTcandidate

*/
case class Deal(Header: org.apache.spark.bts.deal.entity.Header,
  Id: String,
  IdScCd: Short,
  CtgyCd: Short,
  BtsTpCd: Short,
  ExtTp: Option[String] = None,
  ExtTpScCd: Option[Short] = None,
  ExtTpDesc: Option[String] = None,
  IsBusTrx: Boolean,
  BusTrxTpCd: Option[Short] = None,
  BtsStsCd: Short,
  ExtSts: String,
  ExtStsScCd: Short,
  Desc: Option[String] = None,
  OrderDate: Option[String] = None,
  CreatedAt: String,
  Context: org.apache.spark.bts.deal.entity.DealContext,
  DealLink: Seq[org.apache.spark.bts.deal.entity.DealLink] = Nil,
  IsCBO: Option[Boolean] = None,
  ReasonCd: Option[Short] = None,
  Reversal: Option[org.apache.spark.bts.deal.entity.DealReversal] = None,
  Detail: Option[org.apache.spark.bts.deal.entity.DealDetail] = None)
      


/** 
*Deal Link* represents classified processing relationship between deals.  Between two particular deals at most one link of specific type is allowed to exist. For the links with specified semantics distinct BTS link types must be defined.
@State QC2passed

*/
case class DealLink(Id: String,
  IdScCd: Short,
  LinkTp: Short,
  ExtLinkTp: Option[String] = None,
  ExtLinkTpScCd: Option[Short] = None,
  RoleScCd: Short)
      


/** 
Transaction Element:
Represents the whole booking record - however only the client side money movement on SAC or client side particular FI movement or reference on SKA is stored (i.e. not the balancing side data done by the accounting booking system).
During the booking:
- the input transaction elements can be enriched with additional data (e.g. particular security position to which the movement was applied)
-also additional transaction elements (movements) can be added which make the booking image complete (e.g. FX and possibly missing double accounting / clearing instances).

The "id" and "idScCD" together form the business unique key on the Transaction Element.
All attributes with String[256] are values from external systems and do not have fixed lengths for their values. For e.g. the "id" value comes from different systems and each of them have their own id definitions.
@State DTcandidate

*/
case class TransactionElement(Header: org.apache.spark.bts.deal.entity.Header,
  Id: String,
  IdScCd: Short,
  TpCd: Short,
  Reference: Option[org.apache.spark.bts.deal.entity.TransationElementReferencedObj] = None,
  BookingSideCd: Option[Short] = None,
  BookingTpCd: Option[Short] = None,
  Qty: Option[BigDecimal] = None,
  QtyUnitCd: Option[Short] = None,
  BookingAmt: Option[org.apache.spark.bts.deal.entity.Amount] = None,
  TrxPrice: Option[org.apache.spark.bts.deal.entity.Amount] = None,
  TradeDate: String,
  ValueDate: Option[String] = None,
  BookingDate: String,
  SettlDate: Option[String] = None,
  BookingId: String,
  BookingIdScCd: Short,
  MarketPrice: Option[org.apache.spark.bts.deal.entity.Amount] = None,
  TrxLink: org.apache.spark.bts.deal.entity.TransactionReference,
  TrxElLink: Seq[org.apache.spark.bts.deal.entity.TransactionElementLink] = Nil,
  Reversal: Option[org.apache.spark.bts.deal.entity.TrxElReversal] = None,
  Detail: Option[org.apache.spark.bts.deal.entity.TransactionElementDetail] = None)
      


/** 
Transaction Element Detail
@State QC2passed

*/
case class TransactionElementDetail(TrxElemAttr: Seq[org.apache.spark.bts.deal.entity.DetailAttribute] = Nil,
  SubEntity: Seq[org.apache.spark.bts.deal.entity.DetailSubEntity] = Nil)
      

