// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.apache.spark.bts.deal.entity


/** 
$Id$
$Revision$
$Date$
$Name$
@Filename DT_IFG001908_BTS_1.xsd
@Generator IFMS 5.0
@GeneratedAt 2016-04-13 06:54:21 UTC

*/


/** 
*Transaction* is a core extension of deal which when processed issue booking requests directly to XBS or DBH. This object contains the attributes on the level of the deal and is parent for the sub-entities with additional detail data.

The "id" and "idScCD" together form the business unique key on the Transaction.
All attributes with String[256] are values from external systems and do not have fixed lengths for their values. For e.g. the "id" value comes from different systems and each of them have their own id definitions.
@State Active

*/
case class TransactionType(Id: String,
  IdScCd: Short,
  TpCd: Short,
  StsCd: Short,
  ReversalOf: Option[org.apache.spark.bts.deal.entity.TransactionReversal] = None,
  BookingDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  ReqDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  LinkToDeal: org.apache.spark.bts.deal.entity.DealReferenceType,
  Detail: Option[org.apache.spark.bts.deal.entity.TransactionDetailType] = None)
      


/** 
Transaction Reversal
@State Active

*/
case class TransactionReversal(Id: String,
  IdScCd: Short,
  ReversalTpCd: Short)
      


/** 
Reference to Deal
@State Active

*/
case class DealReferenceType(Id: String,
  IdScCd: Short,
  CtgyCd: Short)
      


/** 
Transaction Detail
@State Active

*/
case class TransactionDetailType(TrxAttr: Seq[org.apache.spark.bts.deal.entity.DetailAttributeType] = Nil,
  SubEntity: Seq[org.apache.spark.bts.deal.entity.DetailSubEntityType] = Nil)
      


/** 
Key value attributes that provide the additional details
@State Active

*/
case class DetailAttributeType(Role: Short,
  Attr: org.apache.spark.bts.deal.entity.AttributeType)
      


/** 
Attribute with Key Value Pair
@State Active

*/
case class AttributeType(Key: Short,
  Value: Seq[org.apache.spark.bts.deal.entity.AttributeValueType] = Nil)
      


/** 
Attribute Value
@State Active

*/
case class AttributeValueType(SeqNo: Short,
  Ctgy: Short,
  BusObjId: Option[String] = None,
  BusObjIdScCd: Option[Short] = None,
  TxtVal: Option[String] = None,
  DecVal: Option[BigDecimal] = None,
  AmtVal: Option[org.apache.spark.bts.deal.entity.Amount] = None,
  Date: Option[javax.xml.datatype.XMLGregorianCalendar] = None)
      


/** 
Detail Sub entity
@State Active

*/
case class DetailSubEntityType(Name: Int,
  SubEntId: String,
  SubEntIdScCd: Int,
  Attr: Seq[org.apache.spark.bts.deal.entity.AttributeType] = Nil)
      


/** 
Exception information
@State QC2passed

*/
case class Exception(Cd: String,
  Desc: String)
      


/** 
Reversal of a Deal
@State QC2passed

*/
case class TrxReversal(Cd: Short,
  ReasonCd: String,
  ReasonText: Option[String] = None,
  RefId: Option[String] = None,
  RefIdScCd: Option[Short] = None,
  UnstructuredRefId: Option[String] = None)
      


/** 
Header Information : contains attributes used to fulfill technical requirements during the processing of the messages
@State QC2passed

*/
case class Header(BulkId: Option[String] = None,
  ProcModeCd: Short)
      


/** 
*Transaction Link* represents classified processing relationship between Transactions.  For the links with specified semantics distinct BTS link types must be defined.
@State QC2passed

*/
case class TransactionLink(Id: String,
  IdScCd: Short,
  LinkTpCd: Short,
  ExtLinkTp: Option[String] = None,
  ExtLinkTpScCd: Option[Short] = None,
  RoleScCd: Short)
      


/** 
Reversal of a Deal
@State QC2passed

*/
case class DealReversal(Cd: Short,
  ReasonCd: Option[String] = None,
  ReasonText: Option[String] = None,
  RefId: Option[String] = None,
  RefIdScCd: Option[Short] = None,
  UnstructuredRefId: Option[String] = None)
      


/** 
Attention Information
@State DTcandidate

*/
case class Attention(Cd: String,
  Desc: String)
      


/** 
*Deal* represents the bank internal image of the external request/trigger/event or its enrichment with processing details or any sub-task/sub-process generated or created on behalves of the original deal. Deal is hence any separately identifiable processing decomposition unit down to the lowest level request which is executed as one logical unit of work - e.g. booking request to XBS (with requests for particular money bookings of GFM) or DBH (with requests for particular instrument bookings/contexts of Securities Order).

The "id" and "idScCD" together form the business unique key on the Deal.
All attributes with String[256] are values from external systems and do not have fixed lengths for their values. For e.g. the "id" value comes from different systems and each of them have their own id definitions.
@State Active

*/
case class DealType(Id: String,
  IdScCd: Short,
  CtgyCd: Short,
  ExtTp: String,
  ExtTpScCd: Int,
  IsBusTrx: Boolean,
  ExtSts: String,
  ExtStsScCd: Short,
  Desc: Option[String] = None,
  LegalDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  Context: org.apache.spark.bts.deal.entity.DealContextType,
  Link: Seq[org.apache.spark.bts.deal.entity.DealLinkType] = Nil,
  Detail: Option[org.apache.spark.bts.deal.entity.DealDetailType] = None)
      


/** 
Generalization of business objects which can be the (primary) deal scope or detail value for a atrtibute/property/key of a deal.
For example: bank legal entity, bank business unit ... bank relationship, banking agreement, financial instrument ...
This object contains for the referenced business object also the mandatory or known parent objects (referenced via internal unique Id) => enables basic searching and aggregation of deals in BTS.
For example:
1. If the referenced object is a FI event then FI and FI issuer could be filled as parent reference too.
2. If the referenced object is SKA then also following parent references could be filled:
bank relationship, bank business unit.
3. If the referenced object is securities position then also following parentv references could be filled:
FI, FI issuer, SKA, bank relationship, bank business unit.
Notes:
- Impementation R.0.2 - discriminator of scope object.
- Counter party of a deal has no derived parent references.
- Attributes of counter party shall be either implemented directly in deal or in a separate entity (with key: deal number, sequence number within deal) but then used only as reference value in deal key value detail.
@State Active

*/
case class DealContextType(BusObjCtgyCd: Short,
  BusObjId: String,
  BusObjIdScCd: Short)
      


/** 
*Deal Link* represents classified processing relationship between deals.  Between two particular deals at most one link of specific type is allowed to exist. For the links with specified semantics distinct BTS link types must be defined.
@State Active

*/
case class DealLinkType(Id: String,
  IdScCd: Short,
  LinkTp: Short,
  ExtLinkTp: Option[String] = None,
  ExtLinkTpScCd: Option[Short] = None,
  RoleScCd: Short)
      


/** 
*Deal Key Value Detail* is a generic ad hoc extension of deal with a value with specified semantics in a "key-value" manner (semantics is specified by the attribute name; value can be free text, currency amount or reference to a business object instance).
Particular implemented structure enables:
1. define values of attributes linked to particular deal instance ("extended attributes of deal") or
2. define equivalent identifiers (synonyms) of chosen deal business unique identifier or
3. one or more references in deal to other business objects ("foreign keys") or
4. define values of attributes of sub-entities associated with/dependent on the deal (e.g. if a deal requires as detail to capture the "merge price" per FI involved in a merger business transaction then it can be done by defining the sub-entity name).
5. store a ordered sequence of values per extension attribute (semantics of the ordering must be defined elsewhere).
Note: If many deals need certain/similar detail data structure with several attributes it should be considered to design and implemented specialization of DealDetailData object to achieve better performance and/or more efficient data validation.
@State Active

*/
case class DealDetailType(DealAttr: Seq[org.apache.spark.bts.deal.entity.DetailAttributeType] = Nil,
  SubEntity: Seq[org.apache.spark.bts.deal.entity.DetailSubEntityType] = Nil)
      


/** 
Transaction Element:
Represents the whole booking record - however only the client side money movement on SAC or client side particular FI movement or reference on SKA is stored (i.e. not the balancing side data done by the accounting booking system).
During the booking:
- the input transaction elements can be enriched with additional data (e.g. particular security position to which the movement was applied)
-also additional transaction elements (movements) can be added which make the booking image complete (e.g. FX and possibly missing double accounting / clearing instances).

The "id" and "idScCD" together form the business unique key on the Transaction Element.
All attributes with String[256] are values from external systems and do not have fixed lengths for their values. For e.g. the "id" value comes from different systems and each of them have their own id definitions.
@State Active

*/
case class TransactionElementType(Id: String,
  IdScCd: Short,
  TpCd: Short,
  ReversalOf: Option[org.apache.spark.bts.deal.entity.TransactionElementReversal] = None,
  Reference: Option[org.apache.spark.bts.deal.entity.TransationElementReferencedObjType] = None,
  BookingSideCd: Option[Short] = None,
  BookingTpCd: Option[Short] = None,
  Qty: Option[BigDecimal] = None,
  BookingAmt: Option[org.apache.spark.bts.deal.entity.Amount] = None,
  TrxPrice: Option[org.apache.spark.bts.deal.entity.Amount] = None,
  ExecTime: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  ValueDate: javax.xml.datatype.XMLGregorianCalendar,
  MarketPrice: Option[org.apache.spark.bts.deal.entity.Amount] = None,
  LinkToTransaction: org.apache.spark.bts.deal.entity.TransactionReferenceType,
  Detail: Option[org.apache.spark.bts.deal.entity.TransactionElementDetailType] = None)
      


/** 
Details of the Transaction Element being reversed
@State Active

*/
case class TransactionElementReversal(Id: String,
  IdScCd: Short,
  ReversalTpCd: Short)
      


/** 
Transaction Element Referenced Business object
@State Active

*/
case class TransationElementReferencedObjType(SacNo: Option[String] = None,
  SacNoScCd: Option[Short] = None,
  FinInstrId: Option[String] = None,
  FinInstrIdScCd: Option[Short] = None,
  SecPosId: Option[String] = None,
  SecPosIdScCd: Option[Short] = None)
      


/** 
Transaction Reference
@State Active

*/
case class TransactionReferenceType(Id: String,
  IdScCd: Short)
      


/** 
Transaction Element Detail
@State Active

*/
case class TransactionElementDetailType(TrxElemAttr: Seq[org.apache.spark.bts.deal.entity.DetailAttributeType] = Nil,
  SubEntity: Seq[org.apache.spark.bts.deal.entity.DetailSubEntityType] = Nil)
      


/** 
*Transaction Element Link* represents classified processing relationship between Transaction Elements.  For the links with specified semantics distinct BTS link types must be defined.
@State DTcandidate

*/
case class TransactionElementLink(Id: String,
  IdScCd: Short,
  LinkTpCd: Short,
  ExtLinkTp: Option[String] = None,
  ExtLinkTpScCd: Option[Short] = None,
  RoleScCd: Short)
      


/** 
Reversal of a Deal
@State QC2passed

*/
case class TrxElReversal(Cd: Short,
  ReasonCd: String,
  ReasonText: Option[String] = None,
  RefId: Option[String] = None,
  RefIdScCd: Option[Short] = None,
  UnstructuredRefId: Option[String] = None)
      


/** 
Request strcuture for the getIntTransferLinkageForTax service
@State DTcandidate

*/
case class GetIntTransferLinkageForTaxReq(AppId: String,
  CorrelationId: Option[String] = None,
  ReqTS: String,
  CifNo: String,
  StartDate: javax.xml.datatype.XMLGregorianCalendar,
  EndDate: javax.xml.datatype.XMLGregorianCalendar)
      


/** 
Response structure for the getIntTransferLinkageForTax service
@State DTcandidate

*/
case class GetIntTransferLinkageForTaxRes(CorrelationId: Option[String] = None,
  ResTS: String,
  CifNo: String,
  Transfer: Seq[org.apache.spark.bts.deal.entity.InternalTransferForTax] = Nil)
      


/** 
Internal Transfer details for Tax
@State QC2passed

*/
case class InternalTransferForTax(SkaNo: String,
  TrxId: String,
  TypeCd: Short,
  LinkedCifNo: String,
  LinkedSkaNo: String,
  LinkedTrxId: String,
  IsCBO: Option[Boolean] = None,
  ReasonCd: Option[Short] = None,
  SettlementDate: Option[javax.xml.datatype.XMLGregorianCalendar] = None)
      

