// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package org.apache.spark.bts.deal.entity


/** 
$Id$
$Revision$
$Date$
$Name$
@Filename IFG001908_BTS_receiveBTDeal_2_0.xsd
@Generator IFMS 5.0
@GeneratedAt 2016-04-13 06:54:21 UTC

*/


case class Message(Deal: org.apache.spark.bts.deal.entity.Deal)
      

